### ISSUE TITLE
About 'Latex' and 'LaTeX'

### ISSUE THREAD

**Issue by TerenceLiu98** [wild-flame/mac-os-x-setup-guide#2]
建議將‘Latex’ 修改為 ‘LaTeX‘。
關於 ‘LaTeX’，我寫過一個關於Mac上配置 ‘LaTeX'的文章，是使用sublime text 作為編輯器的，供參考https://www.jianshu.com/p/b1e3b029ded5

**Comment by wild-flame** [comment]
@TerenceLiu98 谢谢你的校正。

p.s. 把你加入 contributor 了，顺便在文章加了一个你那篇简书的链接在后面。
